services:
  backend:
    build:
      # Apontando para a pasta exata onde está o projeto Java
      context: ./api-java/flowpay-atendimentos
      dockerfile: Dockerfile
    container_name: flowpay-api
    ports:
      - "8080:8080"
    networks:
      - flowpay-network
    restart: unless-stopped

  frontend:
    build:
      # Apontando para a pasta exata onde está o projeto React
      context: ./painel-web
      dockerfile: Dockerfile
    container_name: flowpay-painel
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - flowpay-network
    restart: unless-stopped

networks:
  flowpay-network:
    driver: bridge
