# Nome da aplicação
spring.application.name=flowpay-atendimentos

# Configurações do Banco de Dados H2 (Em memória)
spring.datasource.url=jdbc:h2:mem:flowpaydb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Configurações do JPA/Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Habilita o console do H2 no navegador (útil para debugar)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console